server:
  port: ${SERVER_PORT:8083}

spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: false

hoge:
  internal:
    customer-base-url: ${CUSTOMER_BASE_URL}
    stock-base-url: ${STOCK_BASE_URL}
