spring:
  application:
    name: hoge-shipping-gateway-api
  profiles:
    default: local

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
